language: go
os:
  - linux
#  - osx
go:
- '1.10.x'
services:
- docker

cache:
  directories:
    - $GOPATH/src/gx

install: true

jobs:
  include:
    - stage: "build and test (1: tests+coverage (all) | 2: tests (w/basic monitor) | 3: tests (w/stateless tracker) | 4: checks | 5: docker | 6: sharness)"
      script:
        - go get -u github.com/mattn/goveralls
        - go get -u golang.org/x/tools/cmd/cover
        - make deps
        - go test -v -race -coverprofile=coverage.out -covermode=count ./...
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - script:
        - go get -u github.com/mattn/goveralls
        - go get -u golang.org/x/tools/cmd/cover
        - make deps
        - go test -race -v -monitor basic .
    - script:
        - go get -u github.com/mattn/goveralls
        - go get -u golang.org/x/tools/cmd/cover
        - make deps
        - go test -race -v . -tracker stateless
    - script:
        - go get -u github.com/golang/lint/golint
        - make deps
        - make check
        - make service
        - make ctl
    - script:
        - make docker
    - script:
        - sudo apt-get update
        - sudo apt-get install -y jq curl
        - make deps
        - make install
        - docker pull ipfs/go-ipfs
        - make test_sharness && make clean_sharness

after_success:
- openssl aes-256-cbc -K $encrypted_5a1cb914c6c9_key -iv $encrypted_5a1cb914c6c9_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
sudo: required
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq
    && cd $(pwd) && snapcraft && snapcraft push *.snap --release edge"
  skip_cleanup: true
